all: px.proxyrenewal

clean:
	cd org.glite.px.proxyrenewal/build && ${MAKE} clean

distclean:
	rm -rf org.glite.px.proxyrenewal/build

px.proxyrenewal: 
	cd org.glite.px.proxyrenewal/build && ${MAKE} && ${MAKE} install

