#!/bin/sh

GLITE_LOCATION=${GLITE_LOCATION:-/opt/glite}
GLITE_LOCATION_VAR=${GLITE_LOCATION_VAR:-/opt/glite/var}

[ -f /etc/glite.conf ] && . /etc/glite.conf
[ -f $GLITE_LOCATION/etc/glite-wms.conf ] && . $GLITE_LOCATION/etc/glite-wms.conf
[ -f $HOME/.glite.conf ] && . $HOME/.glite.conf

PROXY_REPOSITORY="$GLITE_LOCATION_VAR/spool/glite-renewd"

start()
{
	if test -z "$GLITE_USER" ;then
		echo 'Error: GLITE_USER is not set'
		echo FAILED
		return 1
	fi

	if [ -n "$GLITE_HOST_CERT" ]; then 
		X509_USER_CERT="$GLITE_HOST_CERT"
		export X509_USER_CERT
	fi
	if [ -n "$GLITE_HOST_KEY" ]; then
		X509_USER_KEY="$GLITE_HOST_KEY"
		export X509_USER_KEY
	fi

	echo -n Starting ProxyRenewal Daemon: glite-proxy-renewd ...

	if [ ! -d "$PROXY_REPOSITORY" ]; then
		mkdir -p $PROXY_REPOSITORY || exit 1
		chown $GLITE_USER $PROXY_REPOSITORY
		chmod 0700 $PROXY_REPOSITORY
	fi
	
	su - $GLITE_USER -c "$GLITE_LOCATION/bin/glite-proxy-renewd \
		-r $PROXY_REPOSITORY" && echo " done"
}

stop()
{
	echo -n "Stopping ProxyRenewal Daemon: glite-proxy-renewd ..."
	PIDS=`ps -C glite-proxy-renewd -o pid --no-heading`
	if [ -z "$PIDS" ]; then
		echo " no process glite-proxy-renewd running"
		exit 1
	else
		kill $PIDS && echo " done"
	fi
}

status()
{
	PIDS=`ps -C glite-proxy-renewd -o pid --no-heading`
	if ps p $PIDS >/dev/null 2>&1; then
		echo glite-proxy-renewd running \($PIDS\)
		return 0
	fi
	
	echo glite-proxy-renewd not running
	return 1
}

case x$1 in
	xstart) start;;
	xstop)  stop;;
	xrestart) stop; start;;
	xstatus) status;;
	x*)	echo usage: $0 start,stop,restart,status >&2
		exit 1;;
esac
